# GCP GKE Cluster Configuration
# Auto-generated by monobase-infra provision wizard

terraform {
  required_version = ">= 1.6"

  backend "gcs" {
    bucket = "parmazip-terraform-state"
    prefix = "cluster/monobase-main"
  }

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

module "gke_cluster" {
  source = "../../terraform/modules/gcp-gke"

  cluster_name       = var.cluster_name
  project_id         = var.project_id
  region             = var.region
  zone               = var.zone
  kubernetes_version = var.kubernetes_version

  network_cidr = var.network_cidr
  node_pools   = var.node_pools

  enable_workload_identity = var.enable_workload_identity

  tags = var.tags
}
