# GCP GKE Cluster - Outputs
# Auto-generated by monobase-infra provision wizard

output "cluster_name" {
  description = "GKE cluster name"
  value       = module.gke_cluster.cluster_name
}

output "cluster_id" {
  description = "GKE cluster ID"
  value       = module.gke_cluster.cluster_id
}

output "cluster_endpoint" {
  description = "GKE cluster endpoint"
  value       = module.gke_cluster.cluster_endpoint
}

output "cluster_ca_certificate" {
  description = "GKE cluster CA certificate"
  value       = module.gke_cluster.cluster_ca_certificate
  sensitive   = true
}

output "configure_kubectl" {
  description = "Command to configure kubectl for this cluster"
  value       = module.gke_cluster.configure_kubectl
}

output "external_secrets_sa_email" {
  description = "External Secrets Operator service account email"
  value       = module.gke_cluster.external_secrets_sa_email
}

output "velero_sa_email" {
  description = "Velero backup service account email"
  value       = module.gke_cluster.velero_sa_email
}

output "cert_manager_sa_email" {
  description = "cert-manager service account email"
  value       = module.gke_cluster.cert_manager_sa_email
}
